// <auto-generated />
namespace AgendamentoOnline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Tabelas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tabelas));
        
        string IMigrationMetadata.Id
        {
            get { return "202306152040551_Tabelas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
