// <auto-generated />
namespace AgendamentoOnline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class correcaoAbstractToVirtual3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(correcaoAbstractToVirtual3));
        
        string IMigrationMetadata.Id
        {
            get { return "202306162025264_correcaoAbstractToVirtual3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
